### PR TITLE
Fix error message

### PR DESCRIPTION
**Pull request by gramalingam**
Fix error message in converter when a non-opset is used in place of opset.

### CODE REVIEW

**Review by justinchuby — APPROVED** [review]

**Comment by gramalingam** [comment]
Strange. The CI is failing with the error message after merging main branch ... wonder what changed?
```
File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/pydata_sphinx_theme/__init__.py", line 877, in run
for node in self.document.findall(matcher):
AttributeError: 'document' object has no attribute 'findall'
```

**Comment by gramalingam** [comment]
@justinchuby : do you have any idea about the failing CI? Thanks!

**Comment by justinchuby** [comment]
I am not completely sure: looks like it is only failing for py37 and it is a failure in pydata_sphinx_theme. I wonder if pydata_sphinx_theme has some quirks in py37, or if anything we changed affected its behavior

**Comment by justinchuby** [comment]
Looks like it fixed itself!

**Comment by gramalingam** [comment]
> Looks like it fixed itself!

I ran the failed ci again, and it succeeded ... but something's strange, if it is non-deterministic.
